CFLAGS = -Wall -pedantic -I../amrnb -I../amrwb
CXXFLAGS = $(CFLAGS)
LDFLAGS = -L../amrnb -L../amrwb

all: amrnb-dec amrnb-enc-sine amrwb-dec

amrnb-dec: amrnb-dec.o wavwriter.o
	$(CXX) -o $@ $+ $(LDFLAGS) -lopencore-amrnb

amrnb-enc-sine: amrnb-enc-sine.o
	$(CC) -o $@ $+ $(LDFLAGS) -lm -lopencore-amrnb

amrwb-dec: amrwb-dec.o wavwriter.o
	$(CXX) -o $@ $+ $(LDFLAGS) -lopencore-amrwb

# To check that both libraries can be linked in statically at the same
# time without duplicate symbols
linkboth: linkboth.o
	$(CC) -static -o $@ $+ $(LDFLAGS) -lopencore-amrnb -lopencore-amrwb

clean:
	rm -f amrnb-dec amrnb-enc-sine amrwb-dec linkboth *.o

